import { state, executeCmd, resetState, triggerNSFW } from './state.js';
import { Sfx } from './audio.js';

export const getCmds = (logEl, canvasRef) => {
    const cmd = (msg, mod, dur = 5000) => executeCmd(msg, mod, logEl, dur);
    
    return {
        "abismo": () => { cmd("Singularidad menor.", {scale: 0.1, bgColor: '#000'}); Sfx.play(40, 'sine', 5, 0.4); },
        "adios": () => { cmd("Despedida.", {alpha: 0, scale: 0.8}); Sfx.play(600, 'sine', 1, 0.2, 200); },
        "agua": () => { cmd("Inmersión.", {overlay: 'rgba(0,50,150,0.4)', particles: 'burbujas', anim: 'flotar'}); Sfx.noise(5, 0.1); },
        "agujeronegro": () => { resetState(); cmd("Singularidad máxima.", {scale: 0, bgColor: '#000'}, 5000); Sfx.play(20, 'sine', 5, 0.5); },
        "alien": () => { cmd("Biología externa.", {filter: 'hue-rotate(130deg) contrast(1.5)', anim: 'flotar'}); Sfx.play(1000, 'sine', 5, 0.1, 1100); },
        "amor": () => { cmd("Oxitocina.", {particles: 'corazones', anim: 'latido', filter: 'saturate(150%) hue-rotate(320deg)'}); Sfx.play(400, 'sine', 1, 0.1, 500); },
        "anime": () => { cmd("Alta frecuencia visual.", {filter: 'saturate(300%) contrast(1.5)', anim: 'vibracion', particles: 'neon'}); Sfx.play(1200, 'square', 0.1, 0.1); setTimeout(()=>Sfx.play(1500,'square',0.1,0.1),100); },
        "animus": () => { cmd("Sincronización.", {bgColor: '#fff', filter: 'brightness(2)', envParticles: 'datos'}); Sfx.play(800, 'square', 0.2, 0.1); },
        "antimateria": () => { cmd("Inversión de masa.", {filter: 'invert(100%)', shadowColor: '#fff', anim: 'vibracion'}); Sfx.play(100, 'sawtooth', 5, 0.2); },
        "antiguo": () => cmd("Deterioro temporal.", {filter: 'sepia(1) contrast(1.5) blur(1px)'}),
        "aplastar": () => { cmd("Presión.", {scaleY: 0.2}); Sfx.noise(0.5, 0.4); },
        "arena": () => { cmd("Tormenta de arena.", {filter: 'sepia(1)', envParticles: 'nieve', bgColor: '#220'}); Sfx.noise(5, 0.3); },
        "argentina": () => { cmd("Celeste y blanco.", {overlay: 'rgba(116,172,223,0.4)', anim: 'balanceo'}); Sfx.play(600, 'sine', 1, 0.1, 800); },
        "asfixia": () => { cmd("Hipoxia.", {overlay: 'rgba(0,0,50,0.5)', anim: 'caos'}); Sfx.noise(5, 0.2); },
        "astral": () => { cmd("Proyección.", {alpha: 0.4, shadowColor: '#0ff', envParticles: 'estrellas', anim: 'flotar'}); Sfx.play(800, 'sine', 5, 0.1); },
        "aura": () => cmd("Emisión energética.", {particles: 'aura_dorada', shadowColor: '#ff0'}),
        "basilisco": () => { cmd("Mirada letal.", {filter: 'grayscale(100%) contrast(2)', overlay: 'rgba(0,0,0,0.5)'}); Sfx.play(50, 'sawtooth', 5, 0.3); },
        "beso": () => { cmd("Contacto.", {scale: 1.5, overlay: 'rgba(255,100,200,0.3)'}); Sfx.play(800, 'sine', 0.2, 0.1); },
        "blanco": () => cmd("Sobreesposición.", {filter: 'brightness(10)'}),
        "borroso": () => cmd("Desenfoque.", {filter: 'blur(8px)'}),
        "bosque": () => { cmd("Fotosíntesis.", {filter: 'sepia(1) hue-rotate(60deg)', envParticles: 'hojas', overlay: 'rgba(0,100,0,0.2)'}); Sfx.noise(5, 0.05); },
        "brasil": () => cmd("Verde y amarillo.", {overlay: 'rgba(0,156,59,0.4)', shadowColor: 'yellow', anim: 'balanceo'}),
        "brazos": () => cmd("Extensión lateral.", {scaleX: 2, scaleY: 0.8}),
        "burbuja": () => cmd("Contención.", {filter: 'drop-shadow(0 0 20px cyan)', anim: 'flotar', overlay: 'rgba(0,255,255,0.1)'}),
        "café": () => { cmd("Estimulación nerviosa.", {anim: 'latido', particles: 'humo', filter: 'sepia(0.8) contrast(1.2)'}); Sfx.play(900, 'sine', 0.5, 0.1, 1000); },
        "caos": () => { cmd("Inestabilidad.", {anim: 'caos', filter: 'hue-rotate(180deg) saturate(300%)'}); Sfx.play(150, 'square', 5, 0.2); },
        "caricia": () => cmd("Estimulación.", {overlay: 'rgba(255,255,255,0.2)', filter: 'brightness(1.1)'}),
        "ceniza": () => { cmd("Desintegración.", {overlay: 'rgba(60,60,60,0.7)', filter: 'grayscale(100%) blur(2px)'}); Sfx.noise(5, 0.2); },
        "chau": () => { cmd("Cierre.", {scale: 0.5, alpha: 0}); Sfx.play(400, 'sine', 1, 0.1, 200); },
        "chiste": () => { cmd("Respuesta cómica.", {anim: 'sacudir', filter: 'saturate(200%)'}); Sfx.play(600, 'sine', 0.2, 0.1, 800); setTimeout(()=>Sfx.play(800,'sine',0.2,0.1,1000), 200); },
        "ciego": () => { cmd("Privación sensorial.", {bgColor: '#000', filter: 'brightness(0)'}); Sfx.play(40, 'sine', 5, 0.3); },
        "clon": () => cmd("Trifurcación.", {clones: 2}),
        "cobre": () => cmd("Oxidación.", {filter: 'sepia(1) hue-rotate(-30deg) saturate(2)'}),
        "coloso": () => { cmd("Crecimiento.", {scale: 3.5}); Sfx.play(80, 'sine', 1, 0.3); },
        "computadora": () => { cmd("Interfaz activa.", {filter: 'contrast(1.5)', envParticles: 'datos', overlay: 'rgba(0,50,0,0.3)'}); Sfx.play(1200, 'square', 0.1, 0.05); },
        "congelado": () => { cmd("Cero absoluto.", {overlay: 'rgba(200,255,255,0.7)', anim: 'none', filter: 'brightness(1.5)'}); Sfx.play(1500, 'sine', 2, 0.1); },
        "crt": () => { cmd("Tubo de rayos catódicos.", {filter: 'contrast(1.5) blur(1px)', envParticles: 'estatica', overlay: 'rgba(0,255,0,0.1)'}); Sfx.noise(5, 0.1); },
        "cyberpunk": () => cmd("Implantes ópticos.", {filter: 'saturate(300%) hue-rotate(290deg)', anim: 'glitch', envParticles: 'lluvia'}),
        "demonio": () => { cmd("Posesión.", {shadowColor: '#f00', particles: 'fuego', filter: 'contrast(2) saturate(2)'}); Sfx.play(60, 'sawtooth', 5, 0.3); },
        "desaturado": () => cmd("Pérdida de color.", {filter: 'grayscale(80%)'}),
        "deseo": () => cmd("Respuesta endocrina.", {anim: 'latido', overlay: 'rgba(255,0,120,0.2)'}),
        "desnudo": () => triggerNSFW(logEl),
        "diablo": () => { cmd("Nivel omega.", {overlay: 'rgba(255,0,0,0.4)', particles: 'fuego', shadowColor: '#f00'}); Sfx.play(70, 'sawtooth', 5, 0.3); },
        "dios": () => { cmd("Supremo.", {filter: 'brightness(2)', shadowColor: '#fff', anim: 'flotar'}); Sfx.play(1000, 'sine', 5, 0.1); },
        "divinidad": () => { cmd("Ascensión.", {filter: 'brightness(5)', scale: 2, anim: 'flotar', shadowColor: '#fff'}); Sfx.play(1200, 'sine', 5, 0.1); },
        "dorado": () => cmd("Oro.", {filter: 'sepia(1) saturate(3) hue-rotate(10deg)', shadowColor: 'gold'}),
        "dracula": () => cmd("Nosferatu.", {filter: 'grayscale(100%) contrast(2)', shadowColor: 'red', particles: 'sangre'}),
        "dragon": () => { cmd("Aliento ígneo.", {particles: 'fuego', shadowColor: 'orange', anim: 'vibracion'}); Sfx.noise(2, 0.5); },
        "drift": () => { cmd("Tracción perdida.", {anim: 'drift', particles: 'humo'}); Sfx.noise(5, 0.3); },
        "eco": () => cmd("Resonancia.", {anim: 'eco'}),
        "elastico": () => cmd("Goma.", {anim: 'gelatina', scaleX: 1.5, scaleY: 0.8}),
        "electrico": () => { cmd("Voltaje.", {particles: 'rayos', filter: 'contrast(1.5)', shadowColor: '#0ff'}); Sfx.noise(0.5, 0.5); },
        "empuje": () => cmd("Fuerza.", {offsetY: -300}),
        "enamorado": () => cmd("Feromonas.", {particles: 'corazones', filter: 'brightness(1.2)'}),
        "enano": () => cmd("Reducción.", {scale: 0.2}),
        "encoger": () => cmd("Contracción.", {scale: 0.5}),
        "enfermo": () => cmd("Patógeno.", {filter: 'sepia(1) hue-rotate(50deg)', anim: 'vibracion'}),
        "espectro": () => cmd("Aparición.", {alpha: 0.2, filter: 'grayscale(100%) blur(2px)', anim: 'flotar'}),
        "espejo": () => cmd("Reflejo.", {transform: 'scaleX(-1)'}),
        "espejismo": () => cmd("Ilusión.", {anim: 'glitch_severo', filter: 'blur(2px)'}),
        "esponja": () => cmd("Estructura porosa.", {overlay: 'rgba(255,255,0,0.6)', scale: 1.5}),
        "estasis": () => { cmd("Tiempo detenido.", {anim: 'none', particles: 'none', envParticles: 'none'}); Sfx.play(1000, 'sine', 0.1, 0.1, 10); },
        "estatica": () => { cmd("Interferencia.", {particles: 'estatica'}); Sfx.noise(5, 0.2); },
        "estirar": () => cmd("Tracción axial.", {scaleY: 2.5, scaleX: 0.5}),
        "estrellas": () => cmd("Bóveda celeste.", {envParticles: 'estrellas', bgColor: '#001'}),
        "estudiante": () => cmd("Déficit de sueño.", {filter: 'grayscale(50%) blur(1px)', anim: 'balanceo', overlay: 'rgba(0,0,50,0.2)'}),
        "facultad": () => cmd("Sobrecarga cognitiva.", {filter: 'contrast(1.5)', envParticles: 'datos', anim: 'respirar'}),
        "fantasia": () => cmd("Alteración fey.", {filter: 'hue-rotate(270deg) saturate(2)', particles: 'burbujas', anim: 'flotar'}),
        "fantasma": () => cmd("Espectro.", {alpha: 0.3, anim: 'flotar', filter: 'grayscale(100%)'}),
        "fenix": () => cmd("Renacimiento.", {particles: 'fuego', shadowColor: '#f80', anim: 'flotar'}),
        "flash": () => cmd("Fuerza de velocidad.", {anim: 'vibracion', shadowColor: '#f00', filter: 'saturate(200%)'}),
        "flotar": () => cmd("Levitación.", {anim: 'flotar'}),
        "fuego": () => { cmd("Combustión.", {overlay: 'rgba(255,80,0,0.4)', particles: 'fuego', anim: 'caos'}); Sfx.noise(5,0.3); },
        "fuerza": () => cmd("Gravedad gravitatoria.", {shadowColor: '#00f', anim: 'vibracion'}),
        "gato": () => { cmd("Agilidad felina.", {anim: 'rebote', scaleX: 1.1}); Sfx.play(900, 'sine', 0.2, 0.1, 1200); },
        "gelatina": () => cmd("Coloide.", {anim: 'gelatina'}),
        "gigante": () => cmd("Macroplasia.", {scale: 3}),
        "glitch": () => { cmd("Fallo.", {anim: 'glitch'}); Sfx.noise(0.2, 0.6); },
        "goku": () => { cmd("Poder latente.", {particles: 'aura_dorada', anim: 'vibracion', shadowColor: '#ff0'}); Sfx.play(200, 'square', 5, 0.1); },
        "gracia": () => cmd("Euforia.", {anim: 'sacudir', filter: 'brightness(1.5)'}),
        "grande": () => cmd("Expansión.", {scale: 2.4}),
        "gravedad": () => cmd("Fuerza G.", {anim: 'terremoto', scale: 1, offsetY: 250}),
        "gravedad0": () => cmd("Microgravedad.", {anim: 'flotar', transform: 'rotate(180deg)'}),
        "grito": () => { cmd("Emisión acústica.", {anim: 'terremoto', scale: 1.6}); Sfx.play(2000, 'sawtooth', 0.8, 0.3, 100); },
        "hablar": () => { cmd("Emisión vocal.", {anim: 'respirar'}); Sfx.play(300, 'sine', 0.2, 0.1); setTimeout(()=>Sfx.play(400,'sine',0.2,0.1), 250); },
        "hacker": () => { cmd("Infiltración.", {envParticles: 'datos', filter: 'contrast(1.5)', overlay: 'rgba(0,50,0,0.5)'}); Sfx.play(1500, 'square', 0.1, 0.05); },
        "heisenberg": () => cmd("Pureza 99.1%.", {filter: 'sepia(1) hue-rotate(30deg) saturate(2)', particles: 'cristales'}),
        "hielo": () => cmd("Criogenia.", {overlay: 'rgba(180,230,255,0.6)', filter: 'brightness(1.6) blur(1px)'}),
        "hipnosis": () => cmd("Sugestión.", {filter: 'hue-rotate(180deg)', anim: 'reloj'}),
        "hola": () => { cmd("Saludo.", {anim: 'rebote', scale: 1.4}); Sfx.play(400, 'sine', 0.3, 0.1, 600); },
        "holograma": () => cmd("Proyección.", {filter: 'opacity(0.6) sepia(1) hue-rotate(160deg)', anim: 'glitch_severo'}),
        "humo": () => { cmd("Combustión incompleta.", {particles: 'humo', filter: 'grayscale(50%)'}); Sfx.noise(5, 0.1); },
        "huracan": () => { cmd("Vórtice anómalo.", {anim: 'tornado', envParticles: 'lluvia'}); Sfx.noise(5, 0.5); },
        "ia": () => { cmd("Red neuronal.", {envParticles: 'datos', filter: 'hue-rotate(90deg) contrast(1.5)'}); Sfx.play(2000, 'square', 0.1, 0.05); setTimeout(()=>Sfx.play(2500, 'square', 0.1, 0.05), 100); },
        "iman": () => cmd("Atracción férrea.", {anim: 'magnetico'}),
        "inmortal": () => cmd("Regeneración.", {anim: 'latido', shadowColor: 'gold', filter: 'brightness(1.5)'}),
        "inteligencia artificial": () => { cmd("Procesamiento.", {envParticles: 'datos', filter: 'hue-rotate(90deg)'}); Sfx.play(2000, 'square', 0.1, 0.05); },
        "interactivo": () => { state.interactive = !state.interactive; logEl.innerText = `Sensores táctiles: ${state.interactive ? 'ON' : 'OFF'}`; },
        "invisible": () => cmd("Camuflaje.", {alpha: 0.05}),
        "invierno": () => cmd("Estación fría.", {envParticles: 'nieve', filter: 'sepia(1) hue-rotate(180deg)'}),
        "japon": () => cmd("Cultura oriental.", {envParticles: 'petalos', filter: 'contrast(1.2)', shadowColor: '#f00'}),
        "japonesa": () => cmd("Estética oriental.", {envParticles: 'petalos', filter: 'saturate(150%)'}),
        "jedi": () => { cmd("Fuerza luminosa.", {shadowColor: '#00f', anim: 'flotar'}); Sfx.play(300, 'sine', 1, 0.2, 400); },
        "kamehameha": () => { cmd("Emisión ki.", {filter: 'brightness(3)', shadowColor: '#0ff', particles: 'rayos'}); Sfx.play(400, 'square', 2, 0.2, 800); },
        "knockout": () => { cmd("Trauma craneal.", {rotation: Math.PI/2, offsetY: 150, filter: 'contrast(2) sepia(1) hue-rotate(-50deg)'}); Sfx.play(1000, 'sine', 0.5, 0.3); },
        "latido": () => { cmd("Contracción miocárdica.", {anim: 'latido'}); Sfx.play(50, 'sine', 0.2, 0.5); },
        "liquido": () => cmd("Fluido.", {anim: 'latido', filter: 'blur(4px)'}),
        "locura": () => cmd("Delirio.", {anim: 'terremoto', filter: 'invert(100%)'}),
        "lodo": () => cmd("Viscosidad.", {overlay: 'rgba(100,50,0,0.6)', anim: 'gelatina'}),
        "lujuria": () => cmd("Instinto primario.", {anim: 'latido', bgColor: '#100', overlay: 'rgba(200,0,0,0.3)'}),
        "luz": () => cmd("Saturación fotónica.", {bgColor: '#fff', filter: 'brightness(3)'}),
        "magia": () => cmd("Arcano.", {shadowColor: '#f0f', particles: 'neon', anim: 'flotar'}),
        "magnetico": () => cmd("Polo de atracción.", {anim: 'magnetico', shadowColor: '#0ff'}),
        "maldicion": () => { cmd("Afección.", {overlay: 'rgba(50,0,50,0.6)', shadowColor: 'purple', anim: 'terremoto'}); Sfx.play(80, 'sawtooth', 5, 0.2); },
        "marioneta": () => cmd("Control externo.", {anim: 'balanceo', rotation: Math.PI/8}),
        "mate": () => cmd("Infusión.", {particles: 'humo', filter: 'sepia(0.5) hue-rotate(60deg)'}),
        "matrix": () => cmd("Simulación.", {overlay: 'rgba(0,255,0,0.2)', filter: 'contrast(2) sepia(1) hue-rotate(80deg)', envParticles: 'datos'}),
        "medusa": () => { cmd("Petrificación progresiva.", {overlay: 'rgba(0,100,0,0.2)', filter: 'sepia(1) hue-rotate(60deg)'}); setTimeout(() => { if(state.filter !== 'none') cmd("Estado sólido.", {filter: 'grayscale(100%) contrast(1.5)'}); }, 2500); },
        "metal": () => cmd("Aleación.", {filter: 'grayscale(100%) contrast(2)', shadowColor: '#fff'}),
        "miedo": () => { cmd("Pánico.", {bgColor: '#000', anim: 'caos', filter: 'grayscale(100%) contrast(2)'}); Sfx.play(60, 'sawtooth', 5, 0.3); },
        "miniatura": () => cmd("Nivel cuántico.", {scale: 0.1}),
        "momia": () => cmd("Desecación.", {filter: 'sepia(1) contrast(1.5)', overlay: 'rgba(200,180,100,0.4)'}),
        "montaña": () => { cmd("Elevación tectónica.", {scale: 2, overlay: 'rgba(100,100,100,0.5)', anim: 'terremoto'}); Sfx.noise(2, 0.5); },
        "mouse": () => { state.interactive = true; cmd("Puntero activo.", {shadowColor: '#0f0'}); Sfx.play(1500, 'square', 0.05, 0.1); },
        "musica": () => { cmd("Ondas sonoras.", {envParticles: 'notas', anim: 'balanceo'}); Sfx.play(440, 'sine', 0.5, 0.1); setTimeout(()=>Sfx.play(554, 'sine', 0.5, 0.1), 500); setTimeout(()=>Sfx.play(659, 'sine', 0.5, 0.1), 1000); },
        "mutacion": () => cmd("Genética alterada.", {scaleX: 1.5, scaleY: 0.8, filter: 'hue-rotate(120deg)'}),
        "naturaleza": () => cmd("Crecimiento.", {envParticles: 'hojas', filter: 'sepia(1) hue-rotate(60deg)'}),
        "negativo": () => cmd("Inversión cromática.", {filter: 'invert(100%)'}),
        "neon": () => cmd("Emisión inducida.", {particles: 'neon', bgColor: '#000', filter: 'contrast(2)'}),
        "niebla": () => { cmd("Visibilidad nula.", {filter: 'blur(5px)', envParticles: 'nieve', overlay: 'rgba(200,200,200,0.5)'}); Sfx.noise(5, 0.05); },
        "nieve": () => cmd("Descenso térmico.", {envParticles: 'nieve', filter: 'brightness(1.2)'}),
        "nitido": () => cmd("Enfoque.", {filter: 'contrast(1.5) saturate(1.5)'}),
        "normal": () => { resetState(); logEl.innerText = "SOMA: Reestablecido."; },
        "nuclear": () => { cmd("Radiación.", {filter: 'hue-rotate(90deg) brightness(1.5)', shadowColor: '#0f0', anim: 'terremoto', particles: 'estatica'}); Sfx.noise(5, 0.5); },
        "ojos": () => cmd("Percepción aumentada.", {filter: 'contrast(2) brightness(1.2)', shadowColor: '#0ff', anim: 'respirar'}),
        "oro": () => cmd("Transmutación.", {overlay: 'rgba(255,215,0,0.4)', filter: 'contrast(1.5) brightness(1.2)'}),
        "oscuridad": () => cmd("Ausencia fotónica.", {bgColor: '#000', filter: 'brightness(0.1)'}),
        "otono": () => cmd("Caída de hojas.", {envParticles: 'hojas', filter: 'sepia(0.8)'}),
        "pantalla": () => cmd("Emisión RGB.", {filter: 'contrast(1.2)', envParticles: 'estatica'}),
        "pantarhei": () => { cmd("Todo fluye.", {anim: 'latido', filter: 'hue-rotate(360deg)'}); canvasRef.style.transition = 'filter 5s linear'; },
        "pasion": () => cmd("Termogénesis.", {anim: 'latido', particles: 'fuego'}),
        "payaso": () => cmd("Comedia.", {filter: 'saturate(300%) hue-rotate(45deg)', scaleX: 1.5, anim: 'rebote'}),
        "pegajoso": () => cmd("Adherencia.", {anim: 'gelatina', overlay: 'rgba(255,100,200,0.4)'}),
        "pequeño": () => cmd("Compresión.", {scale: 0.5}),
        "perro": () => { cmd("Entusiasmo canino.", {anim: 'rebote', scaleX: 1.1}); Sfx.play(400, 'square', 0.1, 0.1); setTimeout(()=>Sfx.play(400, 'square', 0.1, 0.1), 150); },
        "pesadilla": () => { resetState(); cmd("Protocolo crítico.", {filter: 'invert(1) contrast(2)', bgColor: '#100'}, 5000); Sfx.play(50, 'sawtooth', 5, 0.4); },
        "pescado": () => cmd("Hábitat acuático.", {filter: 'sepia(1) hue-rotate(180deg)', particles: 'burbujas', anim: 'flotar'}),
        "pez": () => cmd("Hábitat acuático.", {filter: 'sepia(1) hue-rotate(180deg)', particles: 'burbujas', anim: 'flotar'}),
        "piano": () => { cmd("Frecuencias armónicas.", {envParticles: 'notas'}); Sfx.play(261.63, 'sine', 1, 0.1); setTimeout(()=>Sfx.play(329.63, 'sine', 1, 0.1), 300); setTimeout(()=>Sfx.play(392.00, 'sine', 1, 0.1), 600); },
        "piedra": () => cmd("Petrificación.", {overlay: 'rgba(100,100,100,0.8)', filter: 'grayscale(100%) contrast(1.2)'}),
        "piernas": () => cmd("Extensión inferior.", {scaleY: 2, scaleX: 0.8, offsetY: -100}),
        "pikachu": () => { cmd("Alta tensión.", {particles: 'rayos', shadowColor: '#ff0', filter: 'saturate(200%)'}); Sfx.play(1000, 'square', 0.1, 0.1); },
        "pixel": () => { cmd("Baja resolución.", {scale: 1, filter: 'contrast(200%)'}); canvasRef.style.width = '200px'; setTimeout(() => canvasRef.style.width = '1200px', 5000); },
        "placer": () => cmd("Endorfinas.", {filter: 'brightness(1.3) contrast(0.8)', anim: 'flotar'}),
        "plata": () => cmd("Cromo.", {filter: 'grayscale(100%) contrast(2) brightness(1.5)', shadowColor: '#fff'}),
        "playa": () => { cmd("Radiación solar.", {filter: 'brightness(1.5) saturate(1.5)', overlay: 'rgba(255,255,0,0.1)'}); Sfx.noise(5, 0.05); },
        "plomo": () => cmd("Densidad.", {filter: 'grayscale(80%)', offsetY: 100, scaleY: 0.8}),
        "polvo": () => cmd("Partículas secas.", {particles: 'polvo', filter: 'sepia(0.5)'}),
        "portal": () => cmd("Agujero de gusano.", {anim: 'reloj', filter: 'hue-rotate(180deg)', scale: 0.5}),
        "primavera": () => cmd("Floración.", {envParticles: 'petalos', filter: 'saturate(200%)'}),
        "programador": () => { cmd("Déficit lumínico.", {filter: 'grayscale(30%) contrast(1.2)', envParticles: 'datos'}); Sfx.play(1200, 'square', 0.05, 0.05); },
        "psicodelia": () => { cmd("Expansión.", {filter: 'hue-rotate(270deg) saturate(500%) contrast(2)'}); Sfx.play(400, 'sine', 5, 0.1, 800); },
        "pulsar": () => cmd("Estrella de neutrones.", {anim: 'latido', filter: 'brightness(3)', particles: 'rayos'}),
        "quemado": () => cmd("Carbonización.", {filter: 'grayscale(100%) brightness(0.2)', particles: 'humo'}),
        "radioactivo": () => cmd("Emisión gamma.", {shadowColor: '#0f0', filter: 'contrast(1.5)', particles: 'estatica'}),
        "rayo": () => { cmd("Descarga.", {bgColor: '#fff', filter: 'brightness(5)', particles: 'rayos'}); Sfx.noise(0.5, 0.8); setTimeout(() => state.bgColor = '#000', 100); },
        "rayosx": () => cmd("Radiación penetrante.", {filter: 'invert(1) grayscale(1) contrast(3)', overlay: 'rgba(0,255,255,0.2)'}),
        "reloj": () => cmd("Bucle temporal.", {anim: 'reloj'}),
        "repeler": () => cmd("Polaridad inversa.", {anim: 'repeler'}),
        "reset": () => { resetState(); logEl.innerText = "SOMA: Purga completa."; Sfx.play(440, 'sine', 0.5, 0.1); },
        "rio": () => { cmd("Corriente de agua.", {filter: 'sepia(1) hue-rotate(180deg)', particles: 'burbujas', anim: 'drift'}); Sfx.noise(5, 0.1); },
        "risa": () => { cmd("Respuesta cómica.", {anim: 'sacudir', filter: 'saturate(150%)'}); Sfx.play(600, 'sine', 0.1, 0.1, 700); setTimeout(()=>Sfx.play(700, 'sine', 0.1, 0.1, 800), 150); },
        "robot": () => cmd("Sintético.", {filter: 'grayscale(1) contrast(2)', overlay: 'rgba(100,100,100,0.4)'}),
        "rojo": () => cmd("Filtro carmesí.", {overlay: 'rgba(255,0,0,0.5)'}),
        "rotar": () => cmd("Inversión de eje.", {rotation: Math.PI}),
        "ruido": () => { cmd("Interferencia estática.", {particles: 'estatica', filter: 'grayscale(100%) contrast(2)'}); Sfx.noise(5, 0.4); },
        "saiyan": () => { cmd("Pico de energía.", {anim: 'terremoto', shadowColor: 'gold', particles: 'fuego'}); Sfx.play(300, 'square', 5, 0.2, 600); },
        "sangre": () => { cmd("Hemorragia.", {overlay: 'rgba(120,0,0,0.5)', particles: 'sangre'}); Sfx.noise(2,0.2); },
        "saturado": () => cmd("Exceso cromático.", {filter: 'saturate(500%)'}),
        "sepia": () => cmd("Fotografía vieja.", {filter: 'sepia(100%)'}),
        "sexo": () => triggerNSFW(logEl),
        "silueta": () => cmd("Contraste.", {filter: 'brightness(0)', shadowColor: '#fff'}),
        "simbionte": () => cmd("Parásito.", {overlay: 'rgba(0,0,0,0.8)', anim: 'gelatina', filter: 'contrast(2)'}),
        "sith": () => { cmd("Lado oscuro.", {shadowColor: '#f00', filter: 'contrast(1.5)', particles: 'rayos'}); Sfx.play(80, 'sawtooth', 5, 0.2); },
        "sombra": () => cmd("Ausencia fotónica.", {overlay: 'rgba(0,0,0,0.85)', filter: 'contrast(250%)'}),
        "sordo": () => { cmd("Aislamiento.", {}); Sfx.play(20000, 'sine', 5, 0); },
        "subacuatico": () => cmd("Presión marina.", {filter: 'sepia(1) hue-rotate(180deg) blur(1px)', particles: 'burbujas', anim: 'flotar'}),
        "sudor": () => cmd("Exudación.", {overlay: 'rgba(255,255,255,0.1)'}),
        "sueño": () => cmd("Fase REM.", {filter: 'blur(4px) brightness(1.2)', anim: 'flotar'}),
        "superman": () => cmd("Kryptoniano.", {anim: 'flotar', shadowColor: '#00f', filter: 'saturate(200%)'}),
        "supernova": () => { cmd("Colapso estelar.", {scale: 4, filter: 'brightness(5)', bgColor: '#fff'}); Sfx.noise(5, 0.8); },
        "teclado": () => { state.interactive = true; cmd("Entrada de datos habilitada.", {envParticles: 'datos'}); Sfx.play(1000, 'square', 0.05, 0.1); },
        "teemo": () => cmd("Visión comprometida.", {filter: 'blur(10px) sepia(1) hue-rotate(80deg)', overlay: 'rgba(50,200,50,0.5)'}),
        "teletransporte": () => { cmd("Salto espacial.", {alpha: 0}); setTimeout(() => state.alpha = 1, 500); },
        "televisor": () => cmd("Tubo de rayos catódicos.", {filter: 'contrast(1.5) blur(1px)', envParticles: 'estatica'}),
        "temblor": () => cmd("Micro-sismos.", {anim: 'vibracion'}),
        "termico": () => cmd("Espectro infrarrojo.", {filter: 'invert(1) hue-rotate(180deg) saturate(4)'}),
        "termo": () => cmd("Recipiente térmico.", {particles: 'humo', filter: 'saturate(1.5)'}),
        "terremoto": () => { cmd("Falla sísmica.", {anim: 'terremoto'}); Sfx.noise(5, 0.4); },
        "thanos": () => cmd("El chasquido.", {particles: 'polvo', filter: 'grayscale(50%)', alpha: 0.1}),
        "titan": () => cmd("Escala colossal.", {scale: 3, offsetY: -100}),
        "tormenta": () => { cmd("Baja presión.", {envParticles: 'lluvia', particles: 'rayos', bgColor: '#112'}); Sfx.noise(5, 0.5); },
        "tornado": () => { cmd("Vórtice.", {anim: 'tornado', envParticles: 'nieve'}); Sfx.noise(5, 0.6); },
        "toxico": () => cmd("Riesgo biológico.", {filter: 'sepia(1) hue-rotate(50deg) saturate(3)', particles: 'burbujas'}),
        "tron": () => cmd("Red", {filter: 'invert(1) hue-rotate(180deg)', shadowColor: '#0ff', bgColor: '#000'}),
        "universidad": () => cmd("Adquisición de conocimiento.", {envParticles: 'datos', filter: 'contrast(1.2)'}),
        "vacio": () => cmd("Nulidad.", {alpha: 0, bgColor: '#000'}),
        "vampiro": () => cmd("Heredero nocturno.", {filter: 'grayscale(100%) contrast(1.5)', shadowColor: '#f00', particles: 'sangre'}),
        "velocidad": () => cmd("Aceleración.", {anim: 'vibracion', filter: 'blur(2px)'}),
        "veneno": () => cmd("Toxicidad.", {filter: 'hue-rotate(110deg) saturate(250%)', overlay: 'rgba(0,100,0,0.3)'}),
        "venom": () => cmd("Simbionte alienígena.", {overlay: 'rgba(0,0,0,0.7)', filter: 'contrast(2)', anim: 'glitch', scale: 1.5}),
        "verano": () => cmd("Ola de calor.", {filter: 'saturate(200%) sepia(0.5)', overlay: 'rgba(255,100,0,0.2)'}),
        "vhs": () => { cmd("Cinta magnética.", {filter: 'contrast(1.5) blur(1px) sepia(0.5)', anim: 'glitch_severo'}); Sfx.noise(5, 0.1); },
        "vibracion": () => cmd("Oscilación.", {anim: 'vibracion'}),
        "viento": () => { cmd("Corriente de aire.", {envParticles: 'hojas', anim: 'drift'}); Sfx.noise(5, 0.2); },
        "volcan": () => { cmd("Erupción.", {particles: 'fuego', envParticles: 'nieve', bgColor: '#200'}); Sfx.noise(5, 0.7); },
        "zombie": () => cmd("Necrosis.", {filter: 'sepia(0.8) hue-rotate(40deg)', particles: 'sangre'}),
        "zzz": () => cmd("Narcolepsia.", {particles: 'zzz', anim: 'flotar', filter: 'brightness(0.5)'})
    };
};