import { target, executeCmd, resetState, triggerNSFW, state, physics } from './state';
import { Sfx } from './audio';
import type { CommandMap } from './types';

export const getCmds = (logEl: HTMLElement): CommandMap => {
    const cmd = (msg: string, mod: Record<string, unknown>, dur: number = 5000): void => executeCmd(msg, mod as Parameters<typeof executeCmd>[1], logEl, dur);

    return {
        "abismo": () => { cmd("Colapso gravitacional local. Caída al vacío.", { pose: 'falling', scaleX: 0.1, scaleY: 0.1, bgColor: '#000', distortion: 1 }); Sfx.wind(5, 0.6); },
        "agua": () => { cmd("Inmersión acuática. Entorno de alta presión.", { pose: 'squat', overlay: 'rgba(0,50,150,0.4)', distortion: 2, anim: 'flotar' }); Sfx.noise(5, 0.1, 'lowpass', 400); },
        "agujeronegro": () => { cmd("Ruptura espacio-tiempo. Atracción absoluta.", { pose: 'falling', scaleX: 0, scaleY: 0, bgColor: '#000', aberration: 10, distortion: 5 }); Sfx.play(20, 'sine', 5, 0.5, null, 0, 'lowpass', 100); },
        "aire": () => { cmd("Corrientes ascendentes. Ingravidez temporal.", { pose: 'falling', anim: 'flotar', envParticles: 'nieve', filter: 'opacity(0.8)' }); Sfx.wind(5, 0.4); },
        "alien": () => { cmd("ADN anómalo detectado. Mutación luminiscente.", { pose: 'pose', filter: 'hue-rotate(130deg) contrast(1.5)', anim: 'flotar', bloom: 1 }); Sfx.play(1000, 'sine', 5, 0.1, 1100, 0, 'highpass', 2000); },
        "amor": () => { cmd("Pico de oxitocina. Calidez sistémica.", { pose: 'happy', anim: 'latido', filter: 'saturate(150%) hue-rotate(320deg)', bloom: 2 }); Sfx.heartbeat(5, 0.5); },
        "animus": () => { cmd("Conexión con memorias ancestrales establecida.", { pose: 'meditating', bgColor: '#fff', envParticles: 'datos', bgLayer: 'grid' }); Sfx.play(800, 'square', 0.2, 0.1); },
        "antimateria": () => { cmd("Inversión de masa. Repulsión de fotones.", { pose: 'disjointed', filter: 'invert(100%)', shadowColor: '#fff', anim: 'vibracion', aberration: 5, bloom: 2 }); Sfx.play(100, 'sawtooth', 5, 0.2); },
        "antiguo": () => cmd("Simulación de desgaste temporal acelerado.", { pose: 'sit', filter: 'sepia(1) contrast(1.5) blur(1px)' }),
        "aplastar": () => { cmd("Presión extrema sobre el eje vertical.", { pose: 'collapsed', scaleY: 0.2 }); Sfx.noise(0.5, 0.4); },
        "arena": () => { cmd("Tormenta del desierto. Visibilidad reducida.", { pose: 'protection', envParticles: 'nieve', bgColor: '#220', distortion: 1 }); Sfx.wind(5, 0.6); },
        "asfixia": () => { cmd("Falta de oxígeno. Nivel crítico.", { pose: 'disjointed', overlay: 'rgba(0,0,50,0.5)', anim: 'caos', aberration: 3 }); Sfx.noise(5, 0.2, 'lowpass', 300); },
        "astral": () => { cmd("Proyección etérea fuera del cuerpo físico.", { pose: 'meditating', alpha: 0.4, shadowColor: '#0ff', envParticles: 'estrellas', anim: 'flotar', bgLayer: 'void' }); Sfx.play(800, 'sine', 5, 0.1); },
        "aura": () => cmd("Emisión de energía biomagnética visible.", { pose: 'overload', shadowColor: '#ff0', bloom: 2 }),
        "auto": () => { cmd("Alta velocidad. Desplazamiento inercial activo.", { pose: 'running', anim: 'drift', particles: 'humo' }); Sfx.noise(5, 0.3); },
        "basilisco": () => { cmd("Contacto visual letal. Parálisis inminente.", { pose: 'protection', filter: 'grayscale(100%) contrast(2)', aberration: 2 }); Sfx.play(50, 'sawtooth', 5, 0.3); },
        "beso": () => { cmd("Contacto físico detectado. Endorfinas al máximo.", { pose: 'happy', scaleX: 1.5, scaleY: 1.5, bloom: 1 }); Sfx.play(800, 'sine', 0.2, 0.1); },
        "blanco": () => cmd("Saturación de luz blanca. Colores purgados.", { pose: 'pose', filter: 'brightness(10)' }),
        "borroso": () => cmd("Lentes desenfocadas. Falla óptica.", { pose: 'subject', filter: 'blur(8px)' }),
        "bosque": () => { cmd("Entorno vegetal. Relajación simulada activa.", { pose: 'meditating', envParticles: 'hojas', overlay: 'rgba(0,100,0,0.2)' }); Sfx.wind(5, 0.2); },
        "burbuja": () => cmd("Cápsula de protección frágil aislante.", { pose: 'squat', anim: 'flotar', overlay: 'rgba(0,255,255,0.1)', distortion: 1 }),
        "cafe": () => { cmd("Estimulantes en el sistema. Aceleración cognitiva.", { pose: 'running', anim: 'latido', filter: 'sepia(0.8) contrast(1.2)' }); Sfx.play(900, 'sine', 0.5, 0.1, 1000); },
        "calor": () => { cmd("Alerta por temperatura elevada. Fatiga térmica.", { pose: 'sit', overlay: 'rgba(255,100,0,0.2)', anim: 'vibracion' }); Sfx.fire(5, 0.2); },
        "cama": () => cmd("Posición horizontal. Modo de recuperación.", { pose: 'lying', filter: 'blur(1px)' }),
        "caos": () => { cmd("Fallo en la estructura lógica. Inestabilidad.", { pose: 'disjointed', anim: 'caos', aberration: 8, distortion: 3 }); Sfx.play(150, 'square', 5, 0.2); },
        "caricia": () => cmd("Estímulo reconfortante. Reducción de tensión.", { pose: 'happy', overlay: 'rgba(255,255,255,0.2)', bloom: 1 }),
        "casa": () => cmd("Entorno seguro y familiar configurado.", { pose: 'meditating', bgColor: '#111', overlay: 'rgba(255,200,100,0.1)' }),
        "ceniza": () => { cmd("Restos de combustión masiva. Ruina ambiental.", { pose: 'sit', filter: 'grayscale(100%) blur(2px)' }); Sfx.noise(5, 0.2); },
        "cerveza": () => cmd("Inhibidores desactivados. Pérdida de equilibrio.", { pose: 'happy', filter: 'sepia(1) hue-rotate(30deg)', anim: 'balanceo' }),
        "chau": () => { cmd("Protocolo de desconexión. Cerrando procesos.", { pose: 'subject', scaleX: 0.5, scaleY: 0.5, alpha: 0 }); Sfx.play(400, 'sine', 1, 0.1, 200); },
        "chiste": () => { cmd("Algoritmo de humor ejecutado con éxito.", { pose: 'happy', anim: 'sacudir' }); Sfx.play(600, 'sine', 0.2, 0.1, 800); },
        "cielo": () => { cmd("Altitud máxima alcanzada. Gravedad mínima.", { pose: 'falling', anim: 'flotar', bgColor: '#002' }); Sfx.wind(5, 0.3); },
        "ciego": () => { cmd("Pérdida de señal visual. Pantalla negra.", { pose: 'protection', bgColor: '#000', filter: 'brightness(0)' }); Sfx.play(40, 'sine', 5, 0.3); },
        "clon": () => cmd("Duplicación de la entidad principal.", { pose: 'pose', clones: 2 }),
        "cobre": () => cmd("Aleación metálica simulada. Oxidación leve.", { pose: 'subject', filter: 'sepia(1) hue-rotate(-30deg) saturate(2)' }),
        "coloso": () => { cmd("Aumento desproporcionado de masa muscular.", { pose: 'overload', scaleX: 3.5, scaleY: 3.5 }); Sfx.play(80, 'sine', 1, 0.3); },
        "comer": () => cmd("Ingesta de nutrientes. Expansión de masa.", { pose: 'squat', scaleX: 1.2, scaleY: 1.2 }),
        "computadora": () => { cmd("Sincronización directa con núcleo de datos.", { pose: 'sit', envParticles: 'datos', bgLayer: 'grid', bloom: 1 }); Sfx.play(1200, 'square', 0.1, 0.05); },
        "congelado": () => { cmd("Temperatura bajo cero. Solidificación de tejidos.", { pose: 'protection', overlay: 'rgba(200,255,255,0.7)', anim: 'none' }); Sfx.play(1500, 'sine', 2, 0.1); },
        "crt": () => { cmd("Filtro de monitor antiguo activado.", { pose: 'pose', filter: 'contrast(1.5) blur(1px)', aberration: 3, bgLayer: 'grid' }); Sfx.noise(5, 0.1); },
        "cyberpunk": () => cmd("Implantes ópticos activos. Mundo de neón.", { pose: 'subject', filter: 'saturate(300%) hue-rotate(290deg)', anim: 'glitch', envParticles: 'lluvia', aberration: 5, bloom: 2 }),
        "demonio": () => { cmd("Posesión por entidad destructiva confirmada.", { pose: 'overload', shadowColor: '#f00', particles: 'fuego', bloom: 2 }); Sfx.fire(5, 0.5); },
        "desaturado": () => cmd("Colores eliminados del espectro visual.", { pose: 'sit', filter: 'grayscale(80%)' }),
        "deseo": () => cmd("Impulsos primarios superando el umbral lógico.", { pose: 'happy', anim: 'latido', overlay: 'rgba(255,0,120,0.2)' }),
        "desnudo": () => triggerNSFW(logEl),
        "dia": () => cmd("Luz solar detectada. Entorno iluminado.", { pose: 'subject', bgColor: '#fff', bloom: 2 }),
        "diablo": () => { cmd("Nivel máximo de inestabilidad y hostilidad.", { pose: 'overload', overlay: 'rgba(255,0,0,0.4)', particles: 'fuego', shadowColor: '#f00' }); Sfx.fire(5, 0.6); },
        "dinero": () => cmd("Recursos ampliados. Mejora de estatus operativo.", { pose: 'overload', shadowColor: '#0f0', bloom: 2 }),
        "dios": () => { cmd("Omnipotencia temporal. Reglas físicas suspendidas.", { pose: 'meditating', shadowColor: '#fff', anim: 'flotar', bloom: 4 }); Sfx.play(1000, 'sine', 5, 0.1); },
        "divinidad": () => cmd("Presencia etérea de orden superior.", { pose: 'meditating', filter: 'brightness(5)', anim: 'flotar' }),
        "dorado": () => cmd("Revestimiento de oro. Alta conductividad.", { pose: 'overload', filter: 'sepia(1) saturate(3) hue-rotate(10deg)' }),
        "dormir": () => { cmd("Desconexión de conciencia. Sueño profundo.", { pose: 'lying', anim: 'flotar', filter: 'brightness(0.5)' }); Sfx.wind(5, 0.1); },
        "dracula": () => cmd("Mutación hematófaga nocturna activada.", { pose: 'fight', filter: 'grayscale(100%) contrast(2)', shadowColor: 'red' }),
        "dragon": () => { cmd("ADN reptil inyectado. Capacidades ignífugas.", { pose: 'overload', particles: 'fuego', anim: 'vibracion', bloom: 2 }); Sfx.fire(5, 0.7); },
        "drift": () => { cmd("Pérdida de tracción controlada.", { pose: 'running', anim: 'drift' }); Sfx.noise(5, 0.3); },
        "eco": () => cmd("Fallo en la unicidad temporal. Sombras pasadas.", { pose: 'subject', clones: 2, alpha: 0.5, distortion: 2 }),
        "elastico": () => cmd("Deformación física permitida por bajo rebote.", { pose: 'pose', anim: 'gelatina', scaleX: 1.5, scaleY: 0.8 }),
        "electrico": () => { cmd("Descargas de alto voltaje en el cuerpo.", { pose: 'overload', particles: 'rayos', shadowColor: '#0ff', bloom: 3 }); Sfx.noise(0.5, 0.5); },
        "empuje": () => { cmd("Impacto kinético fuerte aplicado.", { pose: 'falling', physicsEnabled: true }); target.offsetY = -300; physics.vy = -30; },
        "enamorado": () => { cmd("Filtro rosado aplicado. Vulnerabilidad aumentada.", { pose: 'happy', filter: 'brightness(1.2)' }); Sfx.heartbeat(5, 0.5); },
        "enano": () => cmd("Estructura comprimida drásticamente.", { pose: 'squat', scaleX: 0.2, scaleY: 0.2 }),
        "encoger": () => cmd("Escala reducida en todos los ejes.", { pose: 'squat', scaleX: 0.5, scaleY: 0.5 }),
        "enfermo": () => cmd("Infección del sistema. Defensas bajas.", { pose: 'sit', filter: 'sepia(1) hue-rotate(50deg)', anim: 'vibracion' }),
        "enojado": () => cmd("Alerta de estrés. Tensión corporal crítica.", { pose: 'overload', filter: 'saturate(200%) hue-rotate(-20deg)', shadowColor: '#f00', anim: 'vibracion' }),
        "espectro": () => cmd("Cuerpo traslúcido. Presencia fantasmal.", { pose: 'secret', alpha: 0.2, anim: 'flotar', distortion: 3 }),
        "espejismo": () => cmd("Ilusión óptica en zona de alto calor.", { pose: 'subject', filter: 'blur(2px)', aberration: 10 }),
        "espejo": () => cmd("Inversión completa de la perspectiva visual.", { pose: 'subject', scaleX: -1 }),
        "esponja": () => cmd("Cuerpo poroso. Absorción de luz.", { pose: 'subject', scaleX: 1.5, scaleY: 1.5 }),
        "estasis": () => { cmd("Congelación temporal. Todo movimiento detenido.", { pose: 'meditating', anim: 'none', envParticles: 'none' }); Sfx.play(1000, 'sine', 0.1, 0.1, 10); },
        "estatica": () => { cmd("Ruido visual. Pérdida de nitidez.", { pose: 'disjointed', aberration: 2 }); Sfx.noise(5, 0.2); },
        "estirar": () => cmd("Deformación extrema hacia arriba.", { pose: 'pose', scaleY: 2.5, scaleX: 0.5 }),
        "estrellas": () => cmd("Bóveda celeste visible. Exposición al cosmos.", { pose: 'meditating', envParticles: 'estrellas', bgLayer: 'void' }),
        "fantasia": () => cmd("Reglas de la física alteradas. Mundo mágico.", { pose: 'subject', filter: 'hue-rotate(270deg) saturate(2)' }),
        "fantasma": () => cmd("Anomalía residual sin cuerpo sólido.", { pose: 'secret', alpha: 0.3, anim: 'flotar', distortion: 2 }),
        "feliz": () => cmd("Nivel de endorfinas óptimo. Sincronía perfecta.", { pose: 'happy', anim: 'rebote' }),
        "fenix": () => { cmd("Regeneración inducida desde cenizas.", { pose: 'overload', shadowColor: '#f80', anim: 'flotar' }); Sfx.fire(5, 0.3); },
        "fiesta": () => cmd("Sobrecarga de estímulos audiovisuales.", { pose: 'happy', anim: 'sacudir', bloom: 3, filter: 'hue-rotate(90deg) saturate(200%)' }),
        "flash": () => cmd("Velocidad de procesamiento multiplicada.", { pose: 'running', anim: 'vibracion', shadowColor: '#f00', aberration: 4 }),
        "flotar": () => cmd("Leyes de gravedad canceladas.", { pose: 'falling', anim: 'flotar' }),
        "frio": () => { cmd("Temperatura bajando. Hipotermia advertida.", { pose: 'protection', overlay: 'rgba(180,230,255,0.6)', envParticles: 'nieve' }); Sfx.wind(5, 0.4); },
        "fuego": () => { cmd("Peligro térmico. Combustión activa.", { pose: 'worried', particles: 'fuego', anim: 'caos' }); Sfx.fire(5, 0.6); },
        "fuerza": () => cmd("Gravedad focalizada. Presencia abrumadora.", { pose: 'overload', shadowColor: '#00f', anim: 'vibracion' }),
        "gato": () => { cmd("Reflejos aumentados. Agilidad máxima.", { pose: 'squat', anim: 'rebote', scaleX: 1.1 }); Sfx.play(900, 'sine', 0.2, 0.1, 1200); },
        "gelatina": () => cmd("Pérdida de esqueleto rígido.", { pose: 'subject', anim: 'gelatina' }),
        "gigante": () => cmd("Escala fuera de los parámetros recomendados.", { pose: 'overload', scaleX: 3, scaleY: 3 }),
        "glitch": () => { cmd("Error de visualización. Corrupción de memoria.", { pose: 'disjointed', anim: 'glitch', aberration: 6 }); Sfx.noise(0.2, 0.6); },
        "goku": () => { cmd("Nivel de poder excediendo lecturas.", { pose: 'overload', anim: 'vibracion', shadowColor: '#ff0' }); Sfx.play(200, 'square', 5, 0.1); },
        "grande": () => cmd("Cuerpo expandido en dos dimensiones.", { pose: 'pose', scaleX: 2.4, scaleY: 2.4 }),
        "gravedad": () => cmd("Motor de físicas y colisiones encendido.", { pose: 'falling', physicsEnabled: true }),
        "gravedad0": () => cmd("Flotación sin anclajes en ninguna dirección.", { pose: 'falling', anim: 'flotar', rotation: Math.PI }),
        "grito": () => { cmd("Ondas sonoras destruyendo los píxeles cercanos.", { pose: 'worried', anim: 'terremoto', scaleX: 1.6, scaleY: 1.6 }); Sfx.play(2000, 'sawtooth', 0.8, 0.3, 100); },
        "hacker": () => { cmd("Acceso no autorizado al backend.", { pose: 'secret', envParticles: 'datos', bgLayer: 'grid', aberration: 2 }); Sfx.play(1500, 'square', 0.1, 0.05); },
        "heisenberg": () => cmd("Niveles químicos inestables detectados.", { pose: 'overload', filter: 'sepia(1) hue-rotate(30deg) saturate(2)' }),
        "hielo": () => cmd("Bloqueo físico. Superficie resbaladiza.", { pose: 'protection', overlay: 'rgba(180,230,255,0.6)' }),
        "hipnosis": () => cmd("Patrones alterando la percepción de la realidad.", { pose: 'subject', anim: 'reloj', distortion: 3 }),
        "hola": () => { cmd("Conexión inicial. Saludo registrado.", { pose: 'happy', anim: 'rebote', scaleX: 1.4, scaleY: 1.4 }); Sfx.play(400, 'sine', 0.3, 0.1, 600); },
        "holograma": () => cmd("Materialización de luz frágil.", { pose: 'pose', filter: 'opacity(0.6) sepia(1) hue-rotate(160deg)', aberration: 3 }),
        "humo": () => { cmd("Partículas suspendidas tapando la cámara.", { pose: 'sit', filter: 'grayscale(50%)' }); Sfx.noise(5, 0.1); },
        "huracan": () => { cmd("Condiciones climáticas de alerta roja.", { pose: 'falling', anim: 'tornado', envParticles: 'lluvia' }); Sfx.wind(5, 0.8); },
        "iman": () => cmd("Fuerza electromagnética persiguiendo el puntero.", { pose: 'pose', anim: 'magnetico' }),
        "inmortal": () => cmd("Barra de vida infinita asegurada.", { pose: 'meditating', anim: 'latido', shadowColor: 'gold' }),
        "interactivo": () => { target.interactive = !target.interactive; logEl.innerText = `Control manual con puntero: ${target.interactive ? 'ACTIVO' : 'INACTIVO'}.`; },
        "invisible": () => cmd("Capa de camuflaje activada. Cero opacidad.", { pose: 'secret', alpha: 0.05 }),
        "invierno": () => { cmd("Clima gélido cargado en el sistema.", { pose: 'protection', envParticles: 'nieve' }); Sfx.wind(5, 0.5); },
        "jedi": () => { cmd("Conexión profunda con la fuerza del motor.", { pose: 'overload', shadowColor: '#00f', anim: 'flotar', bloom: 2 }); Sfx.play(300, 'sine', 1, 0.2, 400); },
        "kamehameha": () => { cmd("Energía condensada a punto de explotar.", { pose: 'overload', shadowColor: '#0ff', particles: 'rayos', bloom: 4 }); Sfx.play(400, 'square', 2, 0.2, 800); },
        "knockout": () => { cmd("Golpe letal. Sistemas motores apagados.", { pose: 'collapsed', rotation: Math.PI / 2, distortion: 2 }); Sfx.play(1000, 'sine', 0.5, 0.3); },
        "latido": () => { cmd("Pulsaciones rítmicas del modelo.", { pose: 'subject', anim: 'latido' }); Sfx.heartbeat(5, 0.4); },
        "liquido": () => cmd("Físicas de fluidos aplicadas al personaje.", { pose: 'subject', anim: 'latido', distortion: 3 }),
        "lluvia": () => { cmd("Clima húmedo. Precipitaciones constantes.", { pose: 'sit', envParticles: 'lluvia' }); Sfx.rain(5, 0.6); },
        "locura": () => cmd("Pérdida de la estabilidad del render.", { pose: 'disjointed', anim: 'terremoto', aberration: 7, distortion: 4 }),
        "lodo": () => cmd("Movimientos frenados por masa densa.", { pose: 'squat', anim: 'gelatina' }),
        "lujuria": () => cmd("Inclinación hacia instintos menos lógicos.", { pose: 'happy', anim: 'latido', overlay: 'rgba(200,0,0,0.3)' }),
        "luna": () => cmd("Ambiente nocturno suave. Luces atenuadas.", { pose: 'meditating', bgColor: '#001', filter: 'sepia(0.5) hue-rotate(180deg)', envParticles: 'estrellas' }),
        "lunes": () => cmd("Carga de estrés pesado. Moral baja.", { pose: 'sit', filter: 'grayscale(80%)', anim: 'balanceo' }),
        "luz": () => cmd("Brillo absoluto tapando la visión.", { pose: 'overload', bgColor: '#fff', bloom: 5 }),
        "magia": () => cmd("Anomalías hermosas en el cálculo de gráficos.", { pose: 'meditating', shadowColor: '#f0f', anim: 'flotar', bloom: 2 }),
        "magnetico": () => cmd("Fuerza de arrastre hacia tu cursor.", { pose: 'pose', anim: 'magnetico' }),
        "maldicion": () => { cmd("Hechizo dañino reduciendo puntos de vida.", { pose: 'disjointed', overlay: 'rgba(50,0,50,0.6)', anim: 'terremoto' }); Sfx.play(80, 'sawtooth', 5, 0.2); },
        "marioneta": () => cmd("Cables invisibles manipulando el cuerpo.", { pose: 'pose', anim: 'balanceo', rotation: Math.PI / 8 }),
        "mate": () => cmd("Infusión tradicional. Pausa para calcular.", { pose: 'meditating', filter: 'sepia(0.5) hue-rotate(60deg)' }),
        "matrix": () => cmd("Ver la simulación desde fuera del código.", { pose: 'pose', envParticles: 'datos', bgLayer: 'grid', aberration: 1 }),
        "medusa": () => { cmd("Petrificación en progreso.", { pose: 'protection', filter: 'sepia(1) hue-rotate(60deg)' }); setTimeout(() => { if (state.filter !== 'none') cmd("Piedra sólida.", { pose: 'subject', filter: 'grayscale(100%) contrast(1.5)' }); }, 2500); },
        "metal": () => cmd("Cubierta indestructible de cromo.", { pose: 'overload', filter: 'grayscale(100%) contrast(2)' }),
        "miedo": () => { cmd("Alerta constante. Desconfianza ambiental.", { pose: 'worried', bgColor: '#000', anim: 'caos', aberration: 3 }); Sfx.play(60, 'sawtooth', 5, 0.3); },
        "miniatura": () => cmd("Versión compacta. Menos píxeles.", { pose: 'squat', scaleX: 0.1, scaleY: 0.1 }),
        "momia": () => cmd("Texturas secas y vendadas.", { pose: 'pose', filter: 'sepia(1) contrast(1.5)' }),
        "montaña": () => { cmd("Base inamovible como roca sólida.", { pose: 'protection', scaleX: 2, scaleY: 2, anim: 'terremoto' }); Sfx.noise(2, 0.5); },
        "muerte": () => cmd("Eliminación forzada del objeto principal.", { pose: 'disjointed', bgColor: '#000', alpha: 0.5, filter: 'grayscale(100%)' }),
        "musica": () => { cmd("Tonos afinados relajando el sistema.", { pose: 'meditating' }); Sfx.play(440, 'sine', 0.5, 0.1); },
        "mutacion": () => cmd("Falla genética. Formas incorrectas.", { pose: 'disjointed', scaleX: 1.5, scaleY: 0.8, distortion: 2 }),
        "naturaleza": () => { cmd("Entorno botánico próspero.", { pose: 'meditating', envParticles: 'hojas' }); Sfx.wind(5, 0.2); },
        "negativo": () => cmd("Paleta de colores invertida matemáticamente.", { pose: 'pose', filter: 'invert(100%)' }),
        "neon": () => cmd("Luces de ciudad futurista brillante.", { pose: 'pose', bgColor: '#000', filter: 'contrast(2)' }),
        "niebla": () => { cmd("Opacidad ambiental alta. Visión bloqueada.", { pose: 'secret', envParticles: 'nieve' }); Sfx.wind(5, 0.3); },
        "nieve": () => { cmd("Hielo fino cayendo. Frio simulado.", { pose: 'protection', envParticles: 'nieve' }); Sfx.wind(5, 0.3); },
        "nitido": () => cmd("Texturas cargadas en 4K. Contraste alto.", { pose: 'subject', filter: 'contrast(1.5) saturate(1.5)' }),
        "noche": () => cmd("Simulación sin luz principal.", { pose: 'collapsed', bgColor: '#000', filter: 'brightness(0.3)' }),
        "normal": () => { resetState(logEl); },
        "nuclear": () => { cmd("Radiación gamma letal destruyendo cámaras.", { pose: 'protection', shadowColor: '#0f0', anim: 'terremoto', aberration: 5, bloom: 3 }); Sfx.noise(5, 0.5); },
        "oro": () => cmd("Valor incalculable. Reflejos metálicos.", { pose: 'overload', overlay: 'rgba(255,215,0,0.4)', bloom: 2 }),
        "oscuridad": () => cmd("Negro absoluto. Cero fotones renderizados.", { pose: 'secret', bgColor: '#000' }),
        "otono": () => cmd("Estación de hojas caídas. Tonos sepia.", { pose: 'sit', envParticles: 'hojas', filter: 'sepia(0.8)' }),
        "pantarhei": () => { cmd("Todo fluye constantemente, nada se detiene.", { pose: 'meditating', anim: 'latido', distortion: 4 }); },
        "pasion": () => cmd("Alta intensidad calórica y vibracional.", { pose: 'overload', anim: 'latido' }),
        "payaso": () => cmd("Comportamiento errático y de entretenimiento.", { pose: 'happy', scaleX: 1.5, anim: 'rebote' }),
        "pegajoso": () => cmd("Fricción máxima. Desplazamiento entorpecido.", { pose: 'squat', anim: 'gelatina' }),
        "pequeño": () => cmd("Reducido para caber en la palma.", { pose: 'squat', scaleX: 0.5, scaleY: 0.5 }),
        "perro": () => { cmd("Instinto animal hiperactivo.", { pose: 'running', anim: 'rebote', scaleX: 1.1 }); Sfx.play(400, 'square', 0.1, 0.1); },
        "pesadilla": () => { resetState(); cmd("Archivos corruptos y terroríficos cargados.", { pose: 'disjointed', bgColor: '#100', aberration: 10, distortion: 3 }, 5000); Sfx.play(50, 'sawtooth', 5, 0.4); },
        "pez": () => { cmd("Adaptación acuática para sobrevivir.", { pose: 'falling', anim: 'flotar', distortion: 2 }); Sfx.noise(5, 0.1, 'lowpass', 400); },
        "piano": () => { cmd("Armonía acústica detectada.", { pose: 'meditating' }); Sfx.play(261.63, 'sine', 1, 0.1); },
        "piedra": () => cmd("Transformación estática y pesada.", { pose: 'protection', filter: 'grayscale(100%) contrast(1.2)' }),
        "pikachu": () => { cmd("Almacenaje eléctrico a punto de estallar.", { pose: 'overload', shadowColor: '#ff0', bloom: 3 }); Sfx.play(1000, 'square', 0.1, 0.1); },
        "pixel": () => { cmd("Calidad retro. Píxeles visibles.", { pose: 'pose', scaleX: 1, filter: 'contrast(200%)' }); },
        "placer": () => cmd("Pico de recompensa neuroquímica.", { pose: 'happy', anim: 'flotar' }),
        "plata": () => cmd("Material pulido tipo espejo.", { pose: 'overload', shadowColor: '#fff' }),
        "plomo": () => cmd("Peso inmenso empujando hacia abajo.", { pose: 'collapsed', physicsEnabled: true, scaleY: 0.8 }),
        "polvo": () => cmd("Falta de limpieza. Descuido ambiental.", { pose: 'sit', filter: 'sepia(0.5)' }),
        "portal": () => cmd("Deformación para viajar a otro lugar.", { pose: 'falling', anim: 'reloj', scaleX: 0.5, scaleY: 0.5, distortion: 5 }),
        "primavera": () => cmd("Clima cálido. Renacimiento estacional.", { pose: 'happy', filter: 'saturate(200%)' }),
        "psicodelia": () => { cmd("Saturación de formas y colores imposibles.", { pose: 'disjointed', aberration: 6, distortion: 4, bloom: 2 }); Sfx.play(400, 'sine', 5, 0.1, 800); },
        "pulsar": () => cmd("Emisión fuerte de luz cósmica.", { pose: 'overload', anim: 'latido', bloom: 5 }),
        "quemado": () => cmd("Daños por alta temperatura permanentes.", { pose: 'sit', filter: 'grayscale(100%) brightness(0.2)' }),
        "radioactivo": () => cmd("Radiación verde tóxica en el ambiente.", { pose: 'disjointed', shadowColor: '#0f0', aberration: 3, bloom: 2 }),
        "rayo": () => { cmd("Carga repentina de energía del cielo.", { pose: 'overload', bgColor: '#fff', bloom: 5 }); Sfx.noise(0.5, 0.8); },
        "rayosx": () => cmd("Visión a través de la piel y capas.", { pose: 'pose', filter: 'invert(1) grayscale(1) contrast(3)' }),
        "reloj": () => cmd("El paso del tiempo visible como rotación.", { pose: 'pose', anim: 'reloj' }),
        "repeler": () => cmd("Rechazo automático a cualquier contacto.", { pose: 'protection', anim: 'repeler' }),
        "reset": () => { resetState(logEl); Sfx.play(440, 'sine', 0.5, 0.1); },
        "rey": () => cmd("Aura de dominancia y control sobre otros.", { pose: 'overload', shadowColor: '#ff0', bloom: 2 }),
        "reyes": () => cmd("Lucha de dominios duplicando la instancia.", { pose: 'overload', clones: 2, shadowColor: '#ff0' }),
        "rio": () => { cmd("Caudal de agua moviendo todo a su paso.", { pose: 'falling', anim: 'drift', distortion: 2 }); Sfx.noise(5, 0.1); },
        "risa": () => { cmd("Reacción alegre intensa.", { pose: 'happy', anim: 'sacudir' }); Sfx.play(600, 'sine', 0.1, 0.1, 700); },
        "robot": () => cmd("Ausencia de humanidad. Frío y calculador.", { pose: 'pose', filter: 'grayscale(1) contrast(2)' }),
        "rojo": () => cmd("Filtro rojo de sangre y alerta.", { pose: 'overload', overlay: 'rgba(255,0,0,0.5)' }),
        "rotar": () => cmd("Puesto de cabeza físicamente.", { pose: 'falling', rotation: Math.PI }),
        "ruido": () => { cmd("Glitches en la señal receptora.", { pose: 'disjointed', aberration: 4 }); Sfx.noise(5, 0.4); },
        "saiyan": () => { cmd("Aumento legendario de capacidades.", { pose: 'overload', anim: 'terremoto', shadowColor: 'gold', bloom: 3 }); Sfx.play(300, 'square', 5, 0.2, 600); },
        "sangre": () => { cmd("Herida crítica. Fuga de fluidos vitales.", { pose: 'disjointed', overlay: 'rgba(120,0,0,0.5)' }); Sfx.noise(2, 0.2); },
        "saturado": () => cmd("Colores empujados más allá de lo natural.", { pose: 'overload', filter: 'saturate(500%)' }),
        "sepia": () => cmd("Tono antiguo y gastado fotográfico.", { pose: 'sit', filter: 'sepia(100%)' }),
        "sexo": () => triggerNSFW(logEl),
        "silueta": () => cmd("Sombras cubriendo todo detalle.", { pose: 'pose', filter: 'brightness(0)', shadowColor: '#fff', bloom: 2 }),
        "simbionte": () => cmd("Organismo extraño recubriendo el traje.", { pose: 'disjointed', anim: 'gelatina', distortion: 1 }),
        "sith": () => { cmd("Aura de rabia y sed de destrucción.", { pose: 'overload', shadowColor: '#f00', bloom: 2 }); Sfx.play(80, 'sawtooth', 5, 0.2); },
        "sol": () => { cmd("Luz y calor extremos. Cuidado.", { pose: 'overload', bgColor: '#fff', bloom: 5, filter: 'saturate(200%) hue-rotate(30deg)' }); Sfx.fire(5, 0.4); },
        "sombra": () => cmd("Perdido en los rincones oscuros.", { pose: 'secret', overlay: 'rgba(0,0,0,0.85)' }),
        "sordo": () => { cmd("Silencio absoluto. Falla en audio.", { pose: 'secret' }); Sfx.play(20000, 'sine', 5, 0); },
        "subacuatico": () => { cmd("Bajo el nivel del mar. Visión distorsionada.", { pose: 'falling', anim: 'flotar', distortion: 3 }); Sfx.noise(5, 0.1, 'lowpass', 300); },
        "sudor": () => cmd("Esfuerzo alto. Necesidad de descanso.", { pose: 'worried', overlay: 'rgba(255,255,255,0.1)' }),
        "sueño": () => { cmd("Estado latente de descanso.", { pose: 'collapsed', anim: 'flotar', distortion: 1 }); Sfx.wind(5, 0.1); },
        "superman": () => cmd("Poderes heroicos activados.", { pose: 'overload', anim: 'flotar', shadowColor: '#00f' }),
        "supernova": () => { cmd("Explosión estelar. Luz cegadora.", { pose: 'falling', scaleX: 4, scaleY: 4, bgColor: '#fff', bloom: 10, aberration: 5 }); Sfx.noise(5, 0.8); },
        "teclado": () => { target.interactive = true; cmd("Modo de tipeo y control activado.", { pose: 'sit', envParticles: 'datos' }); Sfx.play(1000, 'square', 0.05, 0.1); },
        "teemo": () => cmd("Trampas tóxicas. Ceguera temporal.", { pose: 'squat', filter: 'blur(10px) sepia(1) hue-rotate(80deg)' }),
        "tele": () => cmd("Consumo mediático prolongado. Aturdimiento.", { pose: 'sit', aberration: 4, bgLayer: 'grid', filter: 'contrast(1.5)' }),
        "teletransporte": () => { cmd("Viaje instantáneo. Parpadeo visual.", { pose: 'falling', alpha: 0, distortion: 5 }); setTimeout(() => target.alpha = 1, 500); },
        "temblor": () => cmd("Suelo inestable. Advertencia de sismo.", { pose: 'worried', anim: 'vibracion' }),
        "termico": () => cmd("Cámara de visión de calor conectada.", { pose: 'overload', filter: 'invert(1) hue-rotate(180deg) saturate(4)' }),
        "termo": () => cmd("Conservación estricta de temperatura.", { pose: 'protection', filter: 'saturate(1.5)' }),
        "terremoto": () => { cmd("Sismo fuerte destruyendo polígonos.", { pose: 'protection', anim: 'terremoto', distortion: 1 }); Sfx.noise(5, 0.4); },
        "thanos": () => cmd("La mitad ha desaparecido en el chasquido.", { pose: 'disjointed', alpha: 0.1, distortion: 2 }),
        "tiempo": () => cmd("Observando cómo corren los segundos.", { pose: 'meditating', anim: 'reloj' }),
        "tierra": () => cmd("Anclado al suelo firme.", { pose: 'squat', physicsEnabled: true, bgColor: '#110' }),
        "titan": () => cmd("Escala masiva por encima del límite.", { pose: 'overload', scaleX: 3, scaleY: 3, offsetY: -100 }),
        "tormenta": () => { cmd("Clima furioso con rayos y viento.", { pose: 'protection', envParticles: 'lluvia', bgColor: '#112', bloom: 2 }); Sfx.rain(5, 0.8); },
        "tornado": () => { cmd("Vientos giratorios destruyendo el paso.", { pose: 'falling', anim: 'tornado', envParticles: 'nieve', distortion: 3 }); Sfx.wind(5, 0.9); },
        "toxico": () => cmd("Gas venenoso alterando pulmones virtuales.", { pose: 'disjointed', aberration: 4, distortion: 2 }),
        "trabajo": () => cmd("Labor repetitiva. Cansancio visible.", { pose: 'sit', filter: 'grayscale(50%)', envParticles: 'datos', aberration: 2 }),
        "triste": () => { cmd("Bajón de ánimos generalizado.", { pose: 'sit', filter: 'grayscale(100%)', envParticles: 'lluvia' }); Sfx.rain(5, 0.4); },
        "tron": () => cmd("Mundo de líneas y luces de neón azules.", { pose: 'pose', shadowColor: '#0ff', bgColor: '#000', aberration: 2, bgLayer: 'grid', bloom: 2 }),
        "vacio": () => { cmd("Cero materia. Entorno purgado.", { pose: 'falling', alpha: 0, bgColor: '#000', bgLayer: 'void' }); Sfx.wind(5, 0.3); },
        "vampiro": () => cmd("Alergia al sol. Sed de sangre.", { pose: 'disjointed', shadowColor: '#f00' }),
        "velocidad": () => cmd("Moviéndose más rápido que el fotograma.", { pose: 'running', anim: 'vibracion', distortion: 2 }),
        "veneno": () => cmd("Daño letal recorriendo el cuerpo.", { pose: 'disjointed', distortion: 2 }),
        "venom": () => cmd("Traje negro vivo y agresivo.", { pose: 'overload', anim: 'glitch', scaleX: 1.5, scaleY: 1.5, distortion: 2 }),
        "verano": () => cmd("Época calurosa. Olas de temperatura altas.", { pose: 'sit', filter: 'saturate(200%) sepia(0.5)' }),
        "vhs": () => { cmd("Cinta gastada de video reproduciendo.", { pose: 'pose', anim: 'glitch', aberration: 8 }); Sfx.noise(5, 0.1); },
        "vibracion": () => cmd("Temblores sin detenerse en el objeto.", { pose: 'worried', anim: 'vibracion' }),
        "viernes": () => cmd("Alivio fin de semana. Recuperación inminente.", { pose: 'happy', anim: 'rebote', bloom: 2, filter: 'saturate(150%)' }),
        "viento": () => { cmd("Ráfagas fuertes empujando la imagen.", { pose: 'falling', envParticles: 'hojas', anim: 'drift' }); Sfx.wind(5, 0.7); },
        "vida": () => { cmd("Regeneración de vida. Entorno sano.", { pose: 'meditating', envParticles: 'hojas', filter: 'saturate(150%)' }); Sfx.heartbeat(5, 0.5); },
        "volcan": () => { cmd("Lava y ceniza amenazando el suelo.", { pose: 'protection', bgColor: '#200', bloom: 2 }); Sfx.fire(5, 0.8); },
        "zombie": () => cmd("Sin mente. Caminante reanimado.", { pose: 'disjointed', distortion: 1 }),
        "zzz": () => { cmd("Descansando para recuperar energía.", { pose: 'collapsed', anim: 'flotar' }); Sfx.wind(5, 0.1); }
    };
};

export const checkCombos = (words: string[], logEl: HTMLElement): string | null => {
    const cmd = (msg: string, mod: Record<string, unknown>, dur: number = 5000): void => executeCmd(msg, mod as Parameters<typeof executeCmd>[1], logEl, dur);
    const has = (w1: string, w2: string): boolean => words.includes(w1) && words.includes(w2);

    if (has('fuego', 'tornado')) {
        cmd("Sinergia: Tormenta Ígnea. Destrucción total.", { pose: 'overload', anim: 'tornado', scaleX: 2, bloom: 4, distortion: 3 });
        Sfx.fire(5, 0.9);
        return 'combo1';
    }
    if (has('agua', 'electrico') || has('agua', 'pikachu')) {
        cmd("Sinergia: Electrocución Acuática masiva.", { pose: 'disjointed', anim: 'vibracion', bgColor: '#005', aberration: 8, bloom: 5 });
        Sfx.noise(5, 0.9);
        return 'combo2';
    }
    if (has('matrix', 'glitch')) {
        cmd("Sinergia: Colapso del Simulador Crítico.", { pose: 'pose', anim: 'glitch', envParticles: 'datos', bgLayer: 'grid', aberration: 15, distortion: 5 });
        Sfx.play(200, 'sawtooth', 5, 0.5);
        return 'combo3';
    }
    if (has('dios', 'diablo')) {
        cmd("Sinergia: Choque de Fuerzas Cósmicas.", { pose: 'meditating', anim: 'flotar', clones: 2, bgLayer: 'void', bloom: 8, aberration: 5, scaleX: 1.5, scaleY: 1.5 });
        Sfx.play(800, 'sine', 5, 0.3, 200);
        return 'combo4';
    }
    return null;
};
